export const bookCategories = {
    FICTION: 'Fiction',
    FANTASY: 'Fantasy',
    ADVENTURE: 'Adventure',
    MYSTERY: 'Mystery',
    BIOGRAPHY: 'Biography',
    HISTORICAL: 'Historical',
    ROMANCE: 'Romance',
    SELF_HELP: 'Self-Help',
    THRILLER: 'Thriller',
    HORROR: 'Horror',
    CHILDRENS: 'Children’s',
    EDUCATIONAL: 'Educational',
    POETRY: 'Poetry',
    RELIGION: 'Religion',
    BUSINESS: 'Business',
};
